<?php

namespace FeedBackBundle\Repository;

/**
 * CollaborateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaborateursRepository extends \Doctrine\ORM\EntityRepository
{
}
