<?php

namespace FeedBackBundle\Repository;

/**
 * CommerciauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommerciauxRepository extends \Doctrine\ORM\EntityRepository
{
}
