<?php

namespace FeedBackBundle\Repository;

/**
 * RHRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RHRepository extends \Doctrine\ORM\EntityRepository
{
}
