<?php

namespace FeedBackBundle\Repository;

/**
 * TMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TMRepository extends \Doctrine\ORM\EntityRepository
{
}
